# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160307_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
