# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_friend_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 7, 20, 26, 51, 990171, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
