# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-created_at']},
        ),
    ]
